### ISSUE TITLE
[iOS] 현재진행상황

### ISSUE THREAD

**Issue by youngminshim-de** [janeljs/todo-list#23]
<img width="600" alt="스크린샷 2021-04-13 오후 8 26 29" src="https://user-images.githubusercontent.com/69951890/114545134-8a0bf900-9c96-11eb-8e24-beb78ae0a8fb.png">

## 작업목록

- [x] Todo TableView 구현 (카드 CellView, 고정된 tableView Header 구현)
- [x] ContainerView를 활용하여 ViewController 재사용
- [x] 카드등록 ModalView 텍스트 입력 구현
- [x] 카드 Model 구현
- [x] 카드 등록기능 구현
- [ ] ContextMenu 구현 (popup까지만 구현, 실제동작은 x)
- [x] Drag & Drop 기능구현 (카드 캐수 카운팅 업데이트 아직 x)

## 고민과해결
* ViewController 를 Todo, Doing, Done 세개로 나누지 않고, 재사용을 위해서
최상위 ViewController 에 같은타입의 하위 ViewController를 3개 생성하여 해결하였다.

* 카드등록 ModalView 또한 모든 TableViewController에서 재사용 할 수 있도록 xib 파일로 만들었으며, 추가버튼을 클릭하면 해당 셀을 추가하도록 NotificationCenter를 이용하였다.

* 카드등록 ModalView 에서 TextView 를 사용하여 여러 줄 입력 시 View 가 늘어나게 구현함
이때, placeHolder 효과를  따로 코드로 넣어줘서 TextField 같은 효과를 주었다.

* 우리의 현재 TableViewController의 구조는 section없이 row로만 이루어져있어, TableViewDatasource 의 tableView(_ moveRowAt) 함수를 이용하였고, 
서로 다른 TableViewController 간의 이동을 위해 TableViewDropDelegate의 tableView(_ performDropWith) 함수를 이용하였다.
여기서 어려웠던 부분은 다른 TableView 간의 이동에 있어서 SourceIndexPath를 얻어내는 것이었는데, DragDelegate 에서 localObject에 처음 선택한 Cell의 정보(dataSource, indexPath, tableView)를 저장함으로써 해결하였다.

## 추가공부할 사항
* Network 구현
* 메뉴버튼 구현(Split View Controller)

## 참고
<img width="600" alt="ezgif com-gif-maker" src="https://user-images.githubusercontent.com/73650994/114564018-e5e07d00-9caa-11eb-886c-e73ceb851e4b.gif">

**Comment by Lia316** [comment]
PR & Merged
